spring.application.name=filescan
# ======================
# SERVER
# ======================
server.port=8080

# ======================
# POSTGRESQL DATABASE
# ======================
spring.datasource.url=jdbc:postgresql://localhost:5432/filescan
spring.datasource.username=dev
spring.datasource.password=devpass
spring.datasource.driver-class-name=org.postgresql.Driver


jwt.secret=9f3c2b1a7d8e4f6c9a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8g9h0
jwt.expiration=3600000

# ======================
# JPA / HIBERNATE
# ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ======================
# FILE UPLOAD LIMITS
# ======================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ======================
# CLAMAV CONFIG (custom)
# ======================
clamav.host=localhost
clamav.port=3310

# ======================
# ASYNC CONFIG (optional tuning)
# ======================
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=100